{% set name = "clize" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 047f5a4473602718ab1b85672a7e15303387178d5a81c275dc429dfac1ecb510

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs >=19.1.0
    - docutils >=0.17.0
    - od
    - python >={{ python_min }}
    - sigtools >=4.0.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - clize
    - clize.tests

about:
  home: https://clize.readthedocs.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Turn functions into command-line interfaces
  dev_url: https://github.com/epsy/clize
  doc_url: https://clize.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - proinsias
